# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/v1/payments
Content-Type: application/json

{
  "customerId": 1,
  "paymentIntent": "CAPTURE",
  "paymentMethod": "CREDIT_CARD",
  "transaction": {
    "amount": {
      "currency": "AUD",
      "amount": 99,
      "scale": 10
    },
    "items": [
      {
        "name": "Apple",
        "price": {
          "currency": "AUD",
          "amount": 10,
          "scale": 10
        },
        "quantity": 5
      },
      {
        "name": "Banana",
        "price": {
          "currency": "AUD",
          "amount": 7,
          "scale": 10
        },
        "quantity": 7
      }
    ]
  }
}

###